export const DATA_SOURCE = 'DATA_SOURCE';
export const CITY_REPOSITORY = 'CITY_REPOSITORY';
export const STATE_REPOSITORY = 'STATE_REPOSITORY';
export const HOLIDAY_REPOSITORY = 'HOLIDAY_REPOSITORY';
